CREATE TYPE "ContactCommercialStatus" AS ENUM (
  'UNVALIDATED',
  'VALIDATED_NO_RESPONSE',
  'VALIDATED_RESPONDS',
  'INTERESTED',
  'NOT_DECISION_MAKER',
  'DECISION_MAKER',
  'REPLACE',
  'DISCARDED'
);

CREATE TYPE "ContactBuyingRole" AS ENUM (
  'UNKNOWN',
  'OPERATIONS',
  'USER',
  'INFLUENCER',
  'DECISION_MAKER',
  'BLOCKER'
);

CREATE TYPE "InteractionOutcome" AS ENUM (
  'NO_RESPONSE',
  'INVALID_PHONE',
  'BOUNCED_EMAIL',
  'VERIFIED_CONTACT',
  'REFERRED_TO_OTHER',
  'CALLBACK_REQUESTED',
  'SHARED_OPERATION',
  'REQUESTED_QUOTE',
  'NO_INTEREST',
  'HAS_CURRENT_VENDOR',
  'OTHER'
);

ALTER TABLE "Contact"
ADD COLUMN "commercialStatus" "ContactCommercialStatus" NOT NULL DEFAULT 'UNVALIDATED',
ADD COLUMN "buyingRole" "ContactBuyingRole" NOT NULL DEFAULT 'UNKNOWN',
ADD COLUMN "lastValidatedAt" TIMESTAMP(3);

ALTER TABLE "Interaction"
ADD COLUMN "outcome" "InteractionOutcome";
