CREATE TYPE "InteractionStageContext" AS ENUM ('INVESTIGATION', 'PROSPECTING', 'OPPORTUNITY', 'POST_SALE');
CREATE TYPE "InteractionDirection" AS ENUM ('OUTBOUND', 'INBOUND', 'INTERNAL');
CREATE TYPE "InteractionPurpose" AS ENUM ('RESEARCH', 'VALIDATION', 'FOLLOW_UP', 'DISCOVERY', 'QUOTE', 'NEGOTIATION', 'RELATIONSHIP', 'TASK', 'OTHER');

ALTER TABLE "Interaction"
ADD COLUMN "stageContext" "InteractionStageContext" NOT NULL DEFAULT 'PROSPECTING',
ADD COLUMN "direction" "InteractionDirection" NOT NULL DEFAULT 'OUTBOUND',
ADD COLUMN "purpose" "InteractionPurpose" NOT NULL DEFAULT 'FOLLOW_UP';
