import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Sidebar } from "@/components/layout/Sidebar";
import { SearchProvider } from "@/components/layout/SearchProvider";
import { Topbar } from "@/components/layout/Topbar";

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="es" suppressHydrationWarning>
        <body
          className="antialiased"
        >
          <SearchProvider>
            <div className="flex min-h-screen bg-muted/40 text-foreground">
              <Sidebar />
              <div className="flex w-full flex-col lg:pl-0">
                <Topbar />
                <main className="flex-1 overflow-auto p-4 md:p-6 lg:p-8">
                  {children}
                </main>
              </div>
              {modal}
            </div>
          </SearchProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
